In [1]:
# !pip install modin

In [2]:
# !pip install modin[ray]

In [3]:
import pandas as pd

In [4]:
%%time
df=pd.read_csv("US_Accidents_March23.csv")

<timed exec>:1: DtypeWarning: Columns (29,30,31,32,33,34,35,36,37,38,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.

CPU times: total: 1min 29s
Wall time: 1min 32s

In [5]:
df

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.010,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.010,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4488968,A-4522970,Source1,2,2022-05-26 19:05:37.000000000,2022-05-26 19:29:00.000000000,28.346923,-81.645414,28.347430,-81.648059,0.165,...,False,False,False,False,False,False,Day,Day,Day,Day
4488969,A-4522971,Source1,2,2022-05-13 17:08:51.000000000,2022-05-13 19:34:33.000000000,28.346931,-81.643954,28.347430,-81.648059,0.252,...,False,False,False,False,False,False,Day,Day,Day,Day
4488970,A-4522972,Source1,2,2022-10-13 06:10:46.000000000,2022-10-13 07:41:32.000000000,40.686636,-73.595125,40.685043,-73.611219,0.850,...,False,False,False,False,False,False,Night,Night,Day,Day
4488971,A-4522973,Source1,2,2022-11-13 19:11:44.000000000,2022-11-13 20:26:44.000000000,32.880114,-96.804063,32.880123,-96.804883,0.048,...,False,True,False,False,True,False,Night,Night,Night,Night
4488972,A-4522974,Source1,2,2022-0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.groupby('Start_Lat')

In [7]:
%%time
df.groupby('Start_Lat').count()

CPU times: total: 17.8 s
Wall time: 18.4 s

,ID,Source,Severity,Start_Time,End_Time,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
Start_Lat,,,,,,,,,,,,,,,,,,,,,
24.554800,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
24.555269,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
24.557400,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
24.559731,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
24.559870,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49.000260,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
49.000504,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
49.000580,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
49.000759,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
49.002201,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1

In [8]:
import os
os.environ["MODIN_ENGINE"] = "ray"

In [9]:
import modin.pandas as pd

In [10]:
%%time
df1=pd.read_csv('US_Accidents_March23.csv')
df1

2026-03-20 16:50:02,364	INFO worker.py:2013 -- Started a local Ray instance.
FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0

CPU times: total: 19.9 s
Wall time: 1min 46s

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.010,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.010,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.010,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6549760,A-6598094,Source1,2,2020-10-14 19:57:30,2020-10-14 20:38:30,41.231313,-77.114635,41.226013,-77.095015,1.083,...,False,False,False,False,False,False,Night,Night,Night,Day
6549761,A-6598095,Source1,2,2020-10-30 23:47:56,2020-10-31 02:25:30,29.463522,-98.621246,29.489470,-98.574620,3.329,...,False,False,False,False,False,False,Night,Night,Night,Night
6549762,A-6598096,Source1,2,2020-12-12 02:10:00,2020-12-12 14:16:58,45.657863,-110.534485,45.675381,-110.515311,1.524,...,False,False,False,False,False,False,Night,Night,Night,Night
6549763,A-6598097,Source1,2,2020-11-25 04:53:06,2020-11-25 06:10:49,39.074968,-76.911324,39.073618,-76.932134,1.120,...,False,False,False,False,False,False,Night,Night,Night,Night
6549764,A-6598098,Source1,4,2020-12-23 00:47:00,2021-12-23 02:32:00,32.556956,-93.705474,32.557328,-93.673586,1.857,...,False,False,False,False,False,False,Night,Night,Night,Night

In [11]:
%%time
df1.groupby('Start_Lat').count()

CPU times: total: 375 ms
Wall time: 465 ms

,ID,Source,Severity,Start_Time,End_Time,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
Start_Lat,,,,,,,,,,,,,,,,,,,,,
24.554800,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
24.555269,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
24.557400,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
24.559731,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
24.559870,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49.000493,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
49.000504,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
49.000580,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
49.000759,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1
49.002201,1,1,1,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,1,1